matrix:
  include:
    - language: rust
      rust: nightly
      script:
        - cargo test --manifest-path ./reverse/Cargo.toml

    - language: go
      go: "1.10"
      script:
        - go build ./frontend/main.go
